# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(804, 620)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setGeometry(QtCore.QRect(0, 0, 801, 581))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabs.sizePolicy().hasHeightForWidth())
        self.tabs.setSizePolicy(sizePolicy)
        self.tabs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabs.setAutoFillBackground(False)
        self.tabs.setStyleSheet("border-color: rgb(45, 45, 45);")
        self.tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabs.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabs.setIconSize(QtCore.QSize(25, 25))
        self.tabs.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabs.setUsesScrollButtons(True)
        self.tabs.setDocumentMode(False)
        self.tabs.setTabsClosable(False)
        self.tabs.setMovable(True)
        self.tabs.setTabBarAutoHide(False)
        self.tabs.setObjectName("tabs")
        self.videoTab = QtWidgets.QWidget()
        self.videoTab.setObjectName("videoTab")
        self.graphicsView = QtWidgets.QGraphicsView(self.videoTab)
        self.graphicsView.setGeometry(QtCore.QRect(80, 100, 640, 360))
        self.graphicsView.setStyleSheet("/*box-shadow: 0 8px 32px 0 rgba( 31, 38, 135, 0.37 );*/\n"
"backdrop-filter: blur( 4px );\n"
"/*-webkit-backdrop-filter: blur( 4px );\n"
"border-radius: 10px;\n"
"border: 1px solid rgba( 255, 255, 255, 0.18 );*/\n"
"background-color: rgb(63, 63, 63);\n"
"border-radius: 10px;")
        self.graphicsView.setObjectName("graphicsView")
        self.btnForward = QtWidgets.QPushButton(self.videoTab)
        self.btnForward.setGeometry(QtCore.QRect(240, 470, 61, 61))
        self.btnForward.setStyleSheet("border-radius:30px;\n"
"image: url(:/forward/fast-forward.png);\n"
"background-color: rgba(0,0,0,200);\n"
"padding:10px;")
        self.btnForward.setText("")
        self.btnForward.setObjectName("btnForward")
        self.btnBackward = QtWidgets.QPushButton(self.videoTab)
        self.btnBackward.setGeometry(QtCore.QRect(80, 470, 61, 61))
        self.btnBackward.setStyleSheet("border-radius:30px;\n"
"image: url(:/forward/fast-backward.png);\n"
"background-color: rgba(0,0,0,200);\n"
"padding:10px;")
        self.btnBackward.setText("")
        self.btnBackward.setObjectName("btnBackward")
        self.btnForward_2 = QtWidgets.QPushButton(self.videoTab)
        self.btnForward_2.setGeometry(QtCore.QRect(160, 470, 61, 61))
        self.btnForward_2.setStyleSheet("border-radius:30px;\n"
"image: url(:/forward/play.png);\n"
"background-color: rgba(0,0,0,200);\n"
"padding:10px;")
        self.btnForward_2.setText("")
        self.btnForward_2.setObjectName("btnForward_2")
        self.horizontalSlider = QtWidgets.QSlider(self.videoTab)
        self.horizontalSlider.setGeometry(QtCore.QRect(110, 430, 581, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.cmbxSpeed = QtWidgets.QComboBox(self.videoTab)
        self.cmbxSpeed.setGeometry(QtCore.QRect(590, 470, 131, 51))
        self.cmbxSpeed.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(56, 56, 56);\n"
"color: rgb(85, 170, 0);")
        self.cmbxSpeed.setEditable(False)
        self.cmbxSpeed.setCurrentText("")
        self.cmbxSpeed.setObjectName("cmbxSpeed")
        self.tabs.addTab(self.videoTab, "")
        self.cameraTab = QtWidgets.QWidget()
        self.cameraTab.setObjectName("cameraTab")
        self.tabs.addTab(self.cameraTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 804, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabs.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Video</span></p></body></html>"))
        self.tabs.setTabText(self.tabs.indexOf(self.videoTab), _translate("MainWindow", "Video"))
        self.tabs.setTabText(self.tabs.indexOf(self.cameraTab), _translate("MainWindow", "Camera"))
import res_rc

app = QApplication(sys.argv)
window = QMainWindow()
window.setGeometry(200,200,801,581)
window.setWindowTitle("Falcon Video Player")

win = Ui_MainWindow()
win.setupUi(window)

window.show()
sys.exit(app.exec_())